# Generated by Django 3.1.4 on 2020-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_name',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
