# Generated by Django 3.1.4 on 2020-12-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201229_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatroom',
            new_name='chat_room',
        ),
    ]
