# Generated by Django 3.1.4 on 2021-01-02 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20201229_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='black_list',
            field=models.ManyToManyField(related_name='banned_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='white_list',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
