# Generated by Django 3.1.4 on 2021-01-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210102_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='white_list',
        ),
    ]
