# Generated by Django 3.1.4 on 2021-01-02 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_chatroom_white_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='banned_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
