# Generated by Django 3.1.4 on 2021-01-03 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20210102_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderator_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
