# Generated by Django 3.1.4 on 2021-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatroom_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='_profile_pending_friend_requests_+', to='chat.Profile'),
        ),
    ]
