# Generated by Django 3.1.4 on 2021-01-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_profile_pending_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pending_friend_requests',
        ),
        migrations.AddField(
            model_name='profile',
            name='outcoming_requests',
            field=models.ManyToManyField(blank=True, related_name='_profile_outcoming_requests_+', to='chat.Profile'),
        ),
    ]
