# Generated by Django 3.1.4 on 2021-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210104_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='outcoming_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_requests', to='chat.Profile'),
        ),
    ]
