# Generated by Django 3.1.4 on 2021-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210104_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.IntegerField(choices=[(0, 'Private chat'), (1, 'Group chat')], default=1),
        ),
    ]
