# Generated by Django 3.1.4 on 2021-01-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210106_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chat_type',
        ),
    ]
