# Generated by Django 3.1.4 on 2021-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.IntegerField(choices=[(0, 'public_chat'), (1, 'private_chat')], default=0),
        ),
    ]
