# Generated by Django 3.1.4 on 2021-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20210107_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
